name = "Die Partei Schleswig-Holstein"
license = "MIT"
licenselink = "https://github.com/mthie/die-partei.sh/theme/die-partei/master/LICENSE"
description = ""
homepage = "https://die-partei.sh/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Martin Thielecke"
  homepage = "mthie.com"
